apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: mhrllp4so-java-springboot
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: mhrllp4so-java-springboot 
  name: mhrllp4so-java-springboot
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: mhrllp4so-java-springboot 
